language: android

env:
  - TERM=dumb

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-21
    - extra
    - addon
    - sys-img-armeabi-v7a-android-21
    - sys-img-x86-android-21
